### PR TITLE
Feat: Add automation to contributor list

### PR DESCRIPTION
**Pull request by amang876**
## Description
Added a GitHub Action to automatically update the contributors list in the README using GitHub's API.

## Related Issue
Issues: #430 

## Motivation and Context
Keeps contributor list up-to-date without manual intervention.

## How Has This Been Tested?
Tested locally and on a staging branch with various scenarios (new contributors, PR merges).

## Types of changes
- [x] New feature (non-breaking)

## Checklist:
- [x] Code follows project style
- [x] Documentation updated
- [x] Tests added and passing

### CODE REVIEW

**Review by aaronchantrill — COMMENTED** [review]
This is interesting, although we already have the same functionality through open collective so I don't think we will be merging this request unless something happens with that. We would also need you to sign the license agreement before we could use this. However, I have added the "hacktoberfest-accepted" label which should be enough to get credit for this request.

**Comment by amang876** [comment]
Thank you for adding the "hacktoberfest-accepted" label! I understand Open Collective manages contributors, but this GitHub Action offers a few unique advantages directly on GitHub:

- **Real-time Sync:** It automatically updates README.md with contributors as they make changes, saving manual effort.
- **Direct Links to Profiles**: Unlike the Open Collective graph, this Action provides direct links to each contributor’s GitHub profile, improving visibility and accessibility.

I've also already signed the license agreement, so we're set on that front. Thank you for considering this enhancement!

**Comment by aaronchantrill** [comment]
@SagarSharma101 The CLA does not think you have signed it. Maybe you were using a different email address or something when you signed it before?

**Comment by amang876** [comment]
image
@aaronchantrill please see i signed it already

**Comment by amang876** [comment]
image
i think the github bot is causing issue

**Comment by aaronchantrill** [comment]
@SagarSharma101 Yes, you are correct, it was the bot. I'm not sure what that's about. Thank you for signing the contributor agreement.

**Comment by aaronchantrill** [comment]
I'm just closing this for now. If anyone wants to resurrect it, please feel free.

**Pull request closed without merging**
