### PR TITLE
Naobian Prep & Organization

### PR DESCRIPTION
**Pull request by AustinCasteel**
## Description

Adjusted the naming of "JASPER_CONFIG" to "NAOMI_CONFIG" as well as moved the config path one dir further from just ~/.naomi/ to ~/.naomi/configs/

>NOTE: This change effects the location of the profile.yml thus breaking naomi if you update but do not move your profile.yml to the new location. Populate can be rerun to place a new profile.yml in the correct location if one does not want to move their configs.

## Motivation and Context

Jasper to Naomi change is not required but preferred for continuity. The config path adjustment is to help organize the Naomi sub dir. Naomi does not directly use the sub dir much unless it is setup to have a virtual or local environments in which a python dir is placed in it. With the coming soon addition of the Naobian img, there are dedicated scripts & configs that need to be stored properly, thus the sub dir needs to be organized.

## How Has This Been Tested?

Through countless testing while developing Naobian.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by aaronchantrill — COMMENTED** [review]
For such a small change, it's actually pretty radical. As written, this would break a lot of stuff for existing installs. I would like more information about the structure you envision for the ~/.naomi (config) folder.

**Review by aaronchantrill — CHANGES_REQUESTED** [review]
Okay, this now attempts to move the config file to the new location, and leaves other directories (like vocabularies) in place. However, I am still getting this error message:
```
$ python -u Naomi.py --local --debug |& tee ~/naomi_git.log
************************************************************
*                    Naomi Assistant                       *
* Made by the Naomi Community, based on the Jasper Project *
* Source code available from                               *
*    https://github.com/NaomiProject/Naomi                 *
************************************************************
WARNING:naomi.application:Deprecated profile file found: '/home/pi/.naomi/profile.yml'. Trying to move it to new location '/home/pi/.naomi/configs/profile.yml'.
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/Naomi/lib/python3.5/shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.naomi/profile.yml' -> '/home/pi/.naomi/configs/profile.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Naomi.py", line 9, in <module>
    naomi.main()
  File "/home/pi/Naomi/naomi/__main__.py", line 85, in main
    print_transcript=p_args.print_transcript
  File "/home/pi/Naomi/naomi/application.py", line 76, in __init__
    shutil.move(old_configfile, new_configfile)
  File "/home/pi/.virtualenvs/Naomi/lib/python3.5/shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "/home/pi/.virtualenvs/Naomi/lib/python3.5/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/pi/.virtualenvs/Naomi/lib/python3.5/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.naomi/config/profile.yml'
```
so basically, the ~/.naomi/config directory does not exist, so moving the file into it fails. There is a section of code around line 35 in application.py where the ~/.naomi directory is being created if it does not exist. I would duplicate that for ~/.naomi/config just before defining the old and new configfile paths.

As a suggestion, I would use os.path.join('config','profile.yml') rather than "config/profile.yml" because it makes the path compatible with windows. I'm not sure how Python3 handles forward slashes in filenames on Windows.

You also need to update naomi/profile.py line 34, otherwise it will still try to read the profile from the old location.

Thanks, it's getting there.

**Comment by aaronchantrill** [comment]
Just as a comment to others, @AustinCasteel and I spoke about the intentions behind this change yesterday.

His vision of how to use the new ~/.naomi/config directory, as I understand it, is that this folder will become the base folder for plugin configuration files. As plugins request settings, these will be stored in a duplicate file structure.

For instance, the plugins/speechhandler/shutdown plugin would store the first_name setting in ~/.naomi/config/plugins/speechhandler/shutdownplugin/profile.yml, and would store the setting as profile.set_profile_var(["first_name"]) and retrieve it as profile.get_profile_var(["first_name"]). This would effectively separate plugin settings, making it more difficult for plugin authors to accidentally overwrite each others settings.

**Comment by AustinCasteel** [comment]
@aaronchantrill I added the fixes and changes you suggested. One thing did stand out though, we call the sub dir CONFIG_PATH and now we have a configs dir so there will most likely be confusion with it. So I changed the old CONFIG_PATH to SUB_PATH so anything that was piggybacking it would not be effected and created a new CONFIG_PATH that is directly linked to the configs dir.

I have worked through all the mentions of config within all of Naomi determining if it is wanting the actual sub dir or the profile.yml file and adjusting things as such. Most of it is self explanatory and easy to figure out. However I do have three files that I am not sure what they are referring to.
`sphinxplugin.py`
`sphinxvocab.py`
`test_sphinxvocab.py`

**Review by aaronchantrill — CHANGES_REQUESTED** [review]
1) Since you have created a new config(file) function which creates files in the ~/.naomi/config folder, it would be better for you to use that on line 74 rather than creating the location from sub, especially since the configs directory location can currently be changed by defining an environment variable (NAOMI_CONFIG)

So
`new_configfile = os.path.join('configs','profile.yml')`
becomes
`new_configfile = paths.config(‘profile.yml’)`

(note that as written, new_configfile becomes `configs/profile.yml` which will generally generate a file not found error, so this should at least change to
`new_configfile = paths.sub(os.path.join('configs','profile.yml'))`)

2) The `.config(` on line 82 is supposed to be a string method. It should be `.format(` not `.config(` or `.sub(`. That’s probably something I did one night when I was too tired to really be coding, so you would be fixing a bug I introduced. It never showed up in testing due to the fact that it only ever shows up if you have a profile.yml file in both the old and new locations.

3) On line 101 you should use variable substitution to put in the actual paths of the old and new profile files. `“{} → {}”.format(old_configfile,new_configfile)` should do it. Remember, the user can override those locations with the NAOMI_SUB and NAOMI_CONFIG environment variables. 

4) Personally, I think you should only allow them to override the NAOMI_SUB path so the rest of the directory structure is more consistent, so change 

`CONFIG_PATH = os.path.expanduser(os.getenv('NAOMI_CONFIG', '~/.naomi/configs'))`

to

`CONFIG_PATH = os.path.join(SUB_PATH, ‘configs'))`

I think it will be too confusing if those paths can be set independently.

5) In naomi/paths.py, I'm kind of on the fence over whether you should still respect the JASPER_CONFIG variable for right now. Something like
`SUB_PATH = os.path.expanduser(os.getenv(‘NAOMI_SUB’,os.getenv(‘JASPER_CONFIG’,”~/.naomi”)))`
would make it so that if there is no NAOMI_SUB environment variable, check to see if there is a JASPER_CONFIG environment variable, and if not, then default to ~/.naomi. I doubt that there is anyone actually using JASPER_CONFIG to set this path, and anyone who is should be sufficiently technical to troubleshoot this. This would allow a Jasper user who has the JASPER_CONFIG value set to install Naomi and not have it try to use the JASPER profile.

6) In naomi/vocabcompiler.py, there is no reason to change the name of the config variable, since it is just being passed through from compile() to compilation_func(). If anything, you might want to call it profile, since it is the parsed contents of the profile.yml file. Profile and config seem to be used interchangeably in the source code. Sub here does not make sense.

That's all I see, and #1 is the only new error this introduces. #2 would fix an existing error. #3 should be done because it's easy and more accurate and helpful with troubleshooting. #4 - 6 are just personal preference.

Thanks!

**Review by aaronchantrill — DISMISSED** [review]
In your error messages on lines 58  and 66 you refer to the ".naomi/configs" directory which is followed directly by the actual path attempting to be accessed. Remember that the .naomi directory can be overridden by the user setting an environment variable.

Assuming the user started Naomi like this:
```terminal
$ NAOMI_SUB=~/ComputerSettings ./Naomi
```
This would result in error messages like:
```
Could not create .naomi/configs dir: /home/pi/ComputerSettings/configs
```
which could be confusing because it kind of looks like two different paths. I think it would be better just to refer to it as the configs directory in these cases.

I'd also like to express some reservations about the names "SUB" and "CONFIG" being used for these directories. In Linux, most programs are now switching to using the ~/.config/{name of the program}/ directory for keeping stored settings and data, so CONFIG would logically refer to the ~/.config/naomi directory, and the ~/.config/naomi/configs directory seems a little repititious. Also, the name SUB is meaningless to me personally. However, it works. Just don't be surprised if some pedantic comes and changes it at some point in the future.

**Review by aaronchantrill — APPROVED** [review]
In your error messages on lines 58  and 66 you refer to the ".naomi/configs" directory which is followed directly by the actual path attempting to be accessed. Remember that the .naomi directory can be overridden by the user setting an environment variable.

Assuming the user started Naomi like this:
```terminal
$ NAOMI_SUB=~/ComputerSettings ./Naomi
```
This would result in error messages like:
```
Could not create .naomi/configs dir: /home/pi/ComputerSettings/configs
```
which could be confusing because it kind of looks like two different paths. I think it would be better just to refer to it as the configs directory in these cases.

I'd also like to express some reservations about the names "SUB" and "CONFIG" being used for these directories. In Linux, most programs are now switching to using the ~/.config/{name of the program}/ directory for keeping stored settings and data, so CONFIG would logically refer to the ~/.config/naomi directory, and the ~/.config/naomi/configs directory seems a little repititious. Also, the name SUB is meaningless to me personally.

It all works. I approve these changes.

**Pull request merged**
