### PR TITLE
Added encryption for email and password | Issue: #16

### PR DESCRIPTION
**Pull request by TSRBerry**
Hey,
I implemented Fernet encryption for email and password using the method previously discussed (https://security.stackexchange.com/questions/79717/store-password-locally-where-how-to-pass-it-securely). I used the get_profile_key() as a salt to get a consistent value for the hash without implementing something new. 

## Related Issue
Issue: #16
## Motivation and Context
Now email and password should be stored securely.

## How Has This Been Tested?
I used my Ubuntu VM again and tried to repopulate my profile with my changes. The only thing I'm worried about is backwards compatibility, but since the email thing was not active the whole time I think it could be fine like this. 
## Screenshot:
image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change) (not sure tho)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by TSRBerry** [comment]
I have no clue what happened to profile.py. I hope everything is fine with it, but if not please tell me.

I also changed the check_mail plugin because it wasn't compatible anymore.

Edit: I think this file is not needed and is just a copy of the other profile.py so I deleted it.
Edit2: It also seems like all my previous commits are in here too, but the final changes are correct.

**Comment by TSRBerry** [comment]
Codacy complains about subprocess but it's necessary for the code so I can't change it this time.

**Comment by aaronchantrill** [comment]
There are a lot of things in the code right now that trip up codacy.

With regard to the issue with subprocess, I created a module called run_command.py located in naomi/run_command.py which can be used instead of subprocess without triggering a failed quality review. The good thing about this is that if we do identify a vulnerability in the way we are using subprocess, it should be fairly easy to isolate. It also encourages not using "shell" which is a bit of a security risk, but manageable if you aren't doing anything with user input.

The plugins/speechhandler/clock/clock.py plugin is a simple example of how run_command can be used. It looks like for all of these, you are blocking until the command completes and then capturing stdout, so you should be able to replace 
```
first_id = subprocess.Popen("sudo dmidecode -t 4 | grep ID | sed 's/.*ID://;s/ //g'", shell=True,
                                stdout=subprocess.PIPE).communicate()[0].decode()
```
with 
```
first_id = run_command(
    [
        "sudo",
        "dmidecode",
        "-t4"
    ],
    capture=1
).stdout.decode('utf-8').strip()
```
although it does not look like you can use pipes when you aren't using a shell, so it would probably make the most sense to do the regex stuff from within python.

I don't think it's a good idea to use sudo here anyway. You can't count on the user having "no password" set up on their user account, or even "sudo" access at all. Debian Buster, for instance, does not install "sudo" by default and just lets users use "su" with root's password directly. "sudo" with "no password" is the standard for the Raspbian pi user, but most users will be prompted for their password, which will block Naomi from operating until the user enters it. Since Naomi can run headless, it might take a while for users to figure out what happened to it. We allow ourselves to do this with populate since all the prompts come right after you start Naomi, but we are working on moving all this configuration stuff to an asynchronous web interface.

Also, the dmidecode is not a standard program. On Arch linux it is part of the extras repository and has to be installed manually. Additionally, on my Virtualbox system running Raspbian Buster, it comes back with
```
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.5 present.
```
which doesn't exactly inspire confidence, especially since you are then grepping it with "ID" which returns an empty string. I assume on a Raspberry Pi it returns something, but I'm not at my Pi right at the moment.

I think what would work better would be something like 
`cat /proc/cpuinfo /proc/partitions /proc/version | sha1sum | cut -d' ' -f1`
as
```
rawtext = run_command(
    [
        "cat",
        "/proc/cpuinfo",
        "/proc/partitions",
        "/proc/version"
    ],
    1
).stdout.decode('utf-8').strip()
```
but then you are still going to have to handle generating the hash from within python.

I'm not sure what happened with Populate. The changelog for your PR lists it, but shows it as unchanged. I don't know why you wouldn't have had it. It's just a throwback to the original documentation anyway. I'd like to get rid of it since Naomi actually gets the settings that need to be set by interrogating the plugins directly.

Thank you for working on this. This is one of the areas that I am most concerned about with regard to Naomi's security. Looks like you are almost there.

**Comment by TSRBerry** [comment]
Everything should be fine now!
I replaced the sudo command with the unique machine id and replaced the ifconfig thing as well.
I added a capture mode 4 to run_command which allows you to pass input to it and just passed my command through that. (Yup, that's definitely the lazy way but at least I didn't need to write new code.) 

If anything still needs some changes, please tell me - but I think that should be it!

**Comment by aaronchantrill** [comment]
Okay, I'll check it out when I get home tonight, so it might be a couple of hours. Thanks!

**Comment by aaronchantrill** [comment]
I've had some problems with blkid, which is not installed by default on my Debian Buster or Arch machines.
I'll try on a Raspberry Pi 3B+ Buster system in the morning.

**Comment by TSRBerry** [comment]
Oh okay, would it be an option to add blkid to apt_requirements.sh?

Edit: I would update the PR with the changes of course. I do think that this would be easier than searching for another method to generate a unique id because files like /proc/cpuinfo are not really unique to one system.

**Comment by aaronchantrill** [comment]
You're right about the /proc files probably not being random enough for our purposes here given that we are targeting the raspberry pi. The only "real" randoms (I know they're not really random, but close enough) I know of are the MAC addresses for the network cards, the UUID's of the drives, and maybe the password of the current user.

The MAC addresses can be gotten via `ifconfig | grep ether` or `ip address | grep ether` but that also grabs the mac addresses of virtual network interfaces. For most people that won't be a problem, but for those who are creating and destroying networks on the box it could be annoying.

As far as blkid, it does appear to be the best way to get the UUID information, other than `ls /dev/disk/by-uuid` and `lsblk -aoUUID`. It occurs to me that as long as you wrap commands in try/except FileNotFoundError blocks you could try a few methods to collect that information, although adding additional methods is probably too much for right now.

The hostname is pretty easy to get from `cat /etc/hostname` and pretty standard in linux, but not particularly random, esp for raspberry pi users who don't bother changing it. Getting the current user's password hash from /etc/shadow is possible, but not guaranteed if they are using some kind of federated login, depending on how they have that set up, and also generally requires sudo.

I'd say that if you can wrap each section in a try/except block, that would be good enough for the moment, better than doing nothing and a good start if someone wants to expand on it later. That way you don't need to require that command, although it would not be bad to add it to apt_requirements with a comment about what it is for.

Have you considered using hashlib for the sha256 hashes? It seems like something like `hashlib.sha256(run_command(["cat","/etc/machine-id"], 1).stdout).hexdigest()` would do about the same thing and require less work if someone wants to port it to another OS.

Another concern I'd like to think about is how to notify the user if this hash has changed. I guess storing a hash of the hash and comparing that would allow us to tell if the hash has changed and notify the user as soon as they start Naomi.

Anyway, for right now if you could wrap your commands in try/except blocks so they don't crash Naomi and just return an empty string if the programs are not installed, that would be enough for me. If you could use hashlib instead of piping to sha256sum that would also be nice, but as long as everything is wrapped so if it fails it does so silently and just generates a logging warning I'll be happy. You are also welcome to add blkid to the apt_requirements file.

Thanks again, I've learned a lot from this.
Aaron

**Comment by TSRBerry** [comment]
Okay!
I added sha256 from hashlib and replaced the shell command for that. The try and except block is now in it as well and util-linux has been added to the requirements.

I think we can tell that the hash changed if it throws InvalidToken when reading the saved hash. So we could tell the user that the hash is different and they have to input their creds again.

Thank you for helping me with this PR!
Julian

**Comment by aaronchantrill** [comment]
Great! I'll test it when I get home in a couple of hours.

Thanks again,
Aaron

**Comment by aaronchantrill** [comment]
Your code seems to be working perfectly as far as encrypting and decrypting.

I'm curious why you are trying to encode the email address, and if you are attempting to encrypt the email username. I have nothing against it, I'm just trying to understand what you are trying to do.

Thank you,
Aaron

**Comment by aaronchantrill** [comment]
I think this is fine, I'm going to go ahead and merge these changes and then take on the email system rewrite directly. Thank you.

**Comment by TSRBerry** [comment]
> Your code seems to be working perfectly as far as encrypting and decrypting.
> 
> I'm curious why you are trying to encode the email address, and if you are attempting to encrypt the email username. I have nothing against it, I'm just trying to understand what you are trying to do.
> 
> Thank you,
> Aaron

If a hacker gets an email address they have the possibility of starting a phishing attack which can have huge impact on the victim. Having the email address means that if an attacker has any password of the victim they will try to get in your account and most people don't have different passwords for their accounts so they could take over a lot of stuff by getting access to your email.
I just want to minimize the risk of those attacks by encrypting the address as well.

Thanks for asking!

**Comment by aaronchantrill** [comment]
Okay, that's what I thought. I'm going to go ahead and encrypt both the email address and email username then, as far as keeping it away from someone stealing the profile. But I'd like to introduce a new class of control that will encrypt the user data but allow the user to see the unencrypted data when editing their profile so they will be able to read the email address and username they have entered for troubleshooting. That probably means that you should have to enter a password to get to the configuration screens.

**Comment by TSRBerry** [comment]
I think I could try to implement that with a similar approach as this one.
This would be a new .py file that allows to edit/get/set values. I probably need to change how the yaml config file is saved, but I think this should be possible for me.

**Comment by aaronchantrill** [comment]
Don't worry about the different settings control. I'm working on that now and should have a new pull request later today. After that, let's take a look at things.

**Comment by aaronchantrill** [comment]
Okay, I've finished my pull request. Thanks for your patience. I'll try to get it merged in soon, but the branch I am requesting the pull from should be totally up to date if you want to look at it.

Beyond that, what are you interested in working on?

Thanks again,
Aaron

**Comment by TSRBerry** [comment]
I will definitely take a look at it, thanks for mentioning it to me!

I am thinking about the Snowboy STT but it's low prio and I don't know if I understand the STT code well enough to update it - but if I am not wrong with my current assumptions it's just a small update.
I like to work on any issue at the moment because I want to finish Hacktoberfest! So if you could recommend an issue to me that I should work on I would appreciate that very much!

**Comment by aaronchantrill** [comment]
Snowboy should be pretty straightforward, and working in modules rather than the core is a good way to learn. Just try running it, and if it is broken, fix it.
How many more PR's do you need for Hacktoberfest?
Other issues that should be fairly straightforward are "#97 Get permission from the user when contacting a new web service", "Fix output from update_translations.py" and "Automatic language configuration", although they are all pretty complex.

One thing I just noticed is that the plugins/stt_trainer/pocketsphinx_adapt/pocketsphinx_adapt.py module has the file locations for files like bw, mllr_solve, map_adapt, etc are correct if you build sphinxtrain yourself, but not if you install it using apt install. If you could go through that file and just verify that those paths can test for the existence of a file and so find the correct version, that would be helpful. For instance, it currently uses the location of '/usr/local/libexec/sphinxtrain/bw' for bw, but when you install using apt, the location is "/usr/lib/sphinxtrain/bw". It needs to be able to figure out which of those paths is correct and use it. You might be able to do one test and set the locations of all those files.

This is part of the ./NaomiSTTTrainer.py program. You will need to run Naomi with either the --save-active-audio flag or `save_active_audio: True` in the profile.yml and use it a little bit so it can collect some audio files and transcriptions. To actually test this part of it, you have to click on the 'Train STT Engines' tab and then the 'Adapt Pocketsphinx' button. If there are any errors, the full error stack trace appears on the command line you launched it from.

Actually, another easy fix right now is that if you run ./NaomiSTTTrainer.py without having used those options to create a database file at ~/.naomi/audiolog/audiolog.db, it crashes out without any real warning about why. It would be helpful to explain to someone that they need to capture some audio clips first before running the program and how to do it.

Once having done that, the automatic language configuration issue should be pretty straightforward for you.

Let me know if I can be helpful.

Thanks!

**Comment by aaronchantrill** [comment]
Another easy fix is that someone just changed the profile keyword variable into a list. This has a couple of odd effects in NaomiSTTTrainer.py, including showing the computer's name in square brackets at the top of the screen, and crashing the program with the following error message:
```
Traceback (most recent call last):
  File "/home/drask/Naomi-git/plugins/stt_trainer/pocketsphinx_adapt/pocketsphinx_adapt.py", line 343, in HandleCommand
    phrases = [profile.get_profile_var(['keyword']).upper()]
AttributeError: 'list' object has no attribute 'upper'
```
So these references need to be changed to `profile.get(['keyword'],'Naomi')[0]` to turn keyword back into a string.

**Comment by aaronchantrill** [comment]
If you can clone a fresh copy of Naomi naomi-dev and test it, I would appreciate it.

**Comment by aaronchantrill** [comment]
Another easy thing - re-enable the populate.py program in applications.py so that it runs when you run ./Naomi.py --repopulate, ./Populate.py or start Naomi without a profile.yml file. This will return the ability to choose a language and select between beeps and voice prompts when running repopulate. It's just commented out right now.

**Comment by TSRBerry** [comment]
> Another easy fix is that someone just changed the profile keyword variable into a list. This has a couple of odd effects in NaomiSTTTrainer.py, including showing the computer's name in square brackets at the top of the screen, and crashing the program with the following error message:
> 
> ```
> Traceback (most recent call last):
>   File "/home/drask/Naomi-git/plugins/stt_trainer/pocketsphinx_adapt/pocketsphinx_adapt.py", line 343, in HandleCommand
>     phrases = [profile.get_profile_var(['keyword']).upper()]
> AttributeError: 'list' object has no attribute 'upper'
> ```
> 
> So these references need to be changed to `profile.get(['keyword'],'Naomi')[0]` to turn keyword back into a string.

Oh that was my bad! I'll fix it as fast as I can.

**Pull request merged**
