### PR TITLE
Updated populate.py

### PR DESCRIPTION
**Pull request by aaronchantrill**
| Status  | Type     | Env Vars Change |
| Ready | Feature | No                        |

## Description

Added ability to choose audio engine
Added ability to choose output device from list and test
Added ability to choose input device from list and test
Fixed location of active_stt engine in profile.yml from the old stt_engine: to the new active_stt: engine:
Changed colors into purpose based functions
Added Naomi/Populate.py to call Naomi/naomi/populate.py

## Related Tickets

* https://github.com/NaomiProject/Naomi/issues/67

## Todos

Add ability to choose passive STT engine separately
Add ability to choose special STT engine for non-standard applications
Write unit tests for functions

- [ ] Tests
- [ ] Documentation

## Deploy Notes

Instead of calling Naomi/naomi/populate.py directly, call Naomi/Populate.py. This is because it was the only way I could load Naomi modules for the querying and testing I wanted to add.

**New scripts**:

Naomi/Populate.py - just calls populate.py, makes it possible to use Naomi resources within populate.py without having to run Naomi.py.

### CODE REVIEW

**Comment by aaronchantrill** [comment]
I also changed the "debug" levels to either "debug" or "error" since "warning" is producing a lot of extra useless output that the normal user doesn't need or want to know about. I'm happy to change that back if people feel like including the warnings is important. This was a change the accidentally got sucked in while I was trying to appease Codacy, but it's something I end up doing anyway on my own copies.

**Review by AustinCasteel — APPROVED** [review]
I don't see any problems with it. You actually did what I was going to do in the coloredformatting.py by mean of setting up defs that are structured accordingly by color & icons so it is consistent as well as it simplifies how we incorporate it in the main naomi files as well as plugins by us and others.

All in all, very good job!

**Comment by aaronchantrill** [comment]
Thanks @Longshotpro2 I appreciate you taking the time to look at it.

**Comment by aaronchantrill** [comment]
Okay, this is tested and I feel pretty good about it. There are plenty of other settings and tests I would like to address, but it seems to be stable.

**Pull request merged**
