### PR TITLE
Removing DeepSpeech from core

### PR DESCRIPTION
**Pull request by AustinCasteel**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by aaronchantrill** [comment]
This looks correct to me. Looks like the Deepspeech plugin has moved to https://github.com/AustinCasteel/deepspeech-stt.git

I am running a test.

**Comment by aaronchantrill** [comment]
Well, I know I had intended to allow plugins to include an "apt_requirements.txt" file, but apparently I never did. I have implemented parsing an apt file and am about to upload it. The deepspeech package you created works fine with it.

**Comment by aaronchantrill** [comment]
If you are done, I'm happy to merge this.

**Comment by AustinCasteel** [comment]
@aaronchantrill Good to go!

**Pull request merged**
