### PR TITLE
Generated G2P Dictionary will be in alphabetically sorted order.

### PR DESCRIPTION
**Pull request by G10DRAS**
Generated G2P Dictionary will be in alphabetically sorted order

### CODE REVIEW

**Comment by TuxSeb** [comment]
Please, fix the pep8 error and i'll merge it ;)

**Comment by TuxSeb** [comment]
did you try this ? it work ?

**Comment by G10DRAS** [comment]
yes

**Comment by TuxSeb** [comment]
can you pr that on jasper-dev please ?  then i'll merge

**Pull request closed without merging**
