### PR TITLE
Small fix for jasper plugins

### PR DESCRIPTION
**Pull request by gospodima**

### CODE REVIEW

**Comment by aaronchantrill** [comment]
The change to shutdown is helpful. This will help the "shutdown" plugin to work with gettext translations. I don't use Wit.ai so I'm not sure why the witai-stt plugin name would need to change to witai, since the documentation uses witai-stt. @TuxSeb - I think you have mentioned using Wit.ai. Do you have any feelings on this?

**Comment by gospodima** [comment]
@aaronchantrill, no other speech-to-text plugin have '-stt' in the name. Also according to original [documentation](http://jasperproject.github.io/documentation/configuration/#witai-stt) (not dev-branch) the name should be without '-stt'.
I also assume that there may be a mistake in the Naomi documentation, since 'google-stt' is used in the configuration file as name of the plugin, while the plugin name is actually 'google' (but I didn’t check if it really causes an error).

**Comment by AustinCasteel** [comment]
The original Jasper documentation has all the speech-to-text listed without the "-stt" in the config and the stt.py reflects the proper slugs, however Naomi is built off of the Jasper2Fork which was a clone of the Jasper-Dev branch. In such Naomi slugs are linked with the directories, so as long as the name in the config matches what is listed in the directory then everything lines up. In the populate process the options you are given list every plugin matched to the way they are named in the plugin.info files for their respective plugins so there should never be a conflict unless someone manually creates their config and doesn't use the name listed in the plugin.info file.

So between the population process & all the plugin.info files, these are the option available:
Plugins

Now with all of that being said, I for one, have not tested every combination of every engine that has been implemented in the dev state we are currently in. So even if the config is created properly whether from the population process or manually does not mean the plugin itself is actually working.


As far a the documentation, the [docs on the website](https://projectnaomi.com/documentation/#configuration) directs you to run the population so everything is done correct and the proper name is placed in the config file based off of what the user selects where as the [docs/wiki here on github](https://github.com/NaomiProject/Naomi/wiki/Speech-To-Text-setup) list them with the -tts & -stt tags. Both of which are correct.

**Comment by TuxSeb** [comment]
@gospodima That's a nice job :+1:  but can you pull request this fix on naomi-dev branche please ? we cannot merge it on the stable branch for now

Thanks you

**Comment by gospodima** [comment]
@TuxSeb 
done.

**Pull request closed without merging**
