### PR TITLE
Added additional utility functions from pull request #519 from jasperproject

### PR DESCRIPTION
**Pull request by andweber**
I think thats an useful pull request originally from Dan Buchta. I took it over from jasperproject

I did some git hacking for getting it over - not sure if it works correctly - but so far looks good.

### CODE REVIEW

**Comment by andreaskoelsch** [comment]
I can't think of a situation when ask() would be useful.

**Comment by andweber** [comment]
Some stt provide a confidence level. If the confidence level is low a plugin can ask if the text was understood correctly.
Or a plugin can ask the user: Shall I provide you more information? Shall I read the message? etc. - I can imagine various scenarios.

**Comment by TuxSeb** [comment]
Humm, interesting, i say "Need Testing"

**Comment by andweber** [comment]
@TuxSeb have you tested it? Can it be merged?

**Comment by TuxSeb** [comment]
@andweber  not yet, but maybe tonight  ;)
and fix the coverage error please :)

**Comment by AustinCasteel** [comment]
Abandoning pull request due to being out of date. Make a new issue & pull request referencing this one if this needs to be reopened.

**Pull request closed without merging**
