### PR TITLE
Moved the Naomi.sh file to ~/.config

### PR DESCRIPTION
**Pull request by AustinCasteel**
## Description

We currently add a call to Naomi.sh to the end of ~/.bashrc to initialize the virtualenvwrapper environment so the user just has to type workon Naomi to get into the environment. Naomi.sh also creates a function in the user's bash shell which allows them to run Naomi by typing Naomi at the command prompt, rather than having to type ~/Naomi/Naomi.py.

This is the only user file we are adding to the Naomi directory. Other than this one file, the user would be able to delete the Naomi directory and re-clone it and it would most likely run fine without rerunning the installer.

## Related Issue

Issue #360

## Motivation and Context

If the user deleted the Naomi folder and then clones it directly from Github, they will have to copy or move the Naomi.sh file to another folder first. Otherwise, they will get an error every time they start a bash session stating that ~/Naomi/Naomi.sh cannot be found.

Sometimes a user needs to reset their working directory by deleting it and re-cloning it from Github, but should not have to go through the setup procedure again.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by aaronchantrill** [comment]
Sorry, busy lately. I'll set up a new Naomi on my Raspberry Pi this weekend and test this pull request.

**Comment by aaronchantrill** [comment]
I'm testing on 2021-10-30-raspios-bullseye at the same time. I'm not sure if the last time I installed Naomi it was on Buster or Bullseye, but I'm pretty sure it was Buster.

**Comment by aaronchantrill** [comment]
I just tried installing Naomi from this pull request.

I used the following commands to clone this pull request and install Naomi:
```
~ $ git clone --origin=upstream https://github.com/NaomiProject/Naomi.git
~ $ cd Naomi
~/Naomi $ git fetch upstream pull/361/head:naomi-sh-to-config
~/Naomi $ git checkout naomi-sh-to-config
~/Naomi $ ./naomi-setup.sh
```
I hit 'S' at the version prompt to keep my currently downloaded version.

Unfortunately, the setup process stalled while downloading python modules. I tried running the installer again to finish setting up the python packages and it said I had already installed Naomi and asked if I really wanted to proceed. I said I did and then hit 'S' to keep the current downloaded version, but it seems like the installer had already deleted the ~/Naomi directory. Didn't move it or rename it, just deleted it. I had to re-download the pull request, then `rm -Rivf ~/.config/naomi` to get it to run again without deleting the ~/Naomi directory.

That's probably nothing to do with this patch, just something to watch out for.

**Comment by aaronchantrill** [comment]
The actual error I keep getting is 
```
  running build_ext
  error: can't find Rust compiler
  
  If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
  
  To update pip, run:
  
      pip install --upgrade pip
  
  and then retry package installation.
  
  If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
  ----------------------------------------
  ERROR: Failed building wheel for libcst
```
so we need to install the rust compiler. I'm not sure if this is required with python on Buster or not.

To install the rust compiler, you need to install curl, build-essential, make and gcc, all of which are already required for Naomi. Then run the following line:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
After that, I was able to install all the python packages from python-requirements.txt.

**Comment by aaronchantrill** [comment]
Ran into an odd problem with Raspbian Bullseye where it continually asks you (verbally) to press ctrl-alt-space to install a screen reader. I assume this is because I installed the standard install with desktop instead of the headless server version. The solution is to kill the piwiz process, then delete the /etc/xdg/autostart/piwiz.desktop file so it doesn't ask again the next time you boot it up. I guess you might be able to plug a keyboard directly into the Pi and press the key combination. You should then be able to disable the screenreader later on, although it really shouldn't say much since nothing is actually happening on the desktop. I'll try logging into a VNC environment and try to see what's going on. Again, this has nothing to do with this pull request, just something odd I noticed.

**Comment by AustinCasteel** [comment]
@aaronchantrill So there is no state management for the install process which is something I would like to do but at the same time if it breaks in the middle of a task then I would need a way to wipe said part and then start from there. Could be done but more complex than what it needs to be.

In terms of the reinstalling as you mentioned. If the installer finds the naomi config structure it flags as already being installed. I can't check for naomi proper dir because you can now have the naomi source located anywhere. When you selected to reinstall, it created a zipped dated backup of the source as well as config structure in ~/.config/naomi_backup/

From there you can get the original source. The reason why that is done is that you don't want conflicting source or config things to affect the install. General user use this is perfectly fine and through the install process, the proper source will be redownloaded as if nothing happened. But since you were using the pr it zipped it up as a backup and then when you selected `S` for the version it did not get a source for you, thus leaving the naomi source dir empty... which caused your issues because it didn't install any requirements because there were no requirement files to install.

So either you need to wipe everything and start fresh, checkout the PR, and install with `S` and you should be good. But if it fails you have to start fresh again, or the other way being once you get to the security setup prompt, move the PR source from the backup back into the naomi source dir and then proceed with the install with `S`. This way the source will be there to install and still be the PR.

**Comment by aaronchantrill** [comment]
I installed the Deep Speech plugin which appeared to work, but keep getting the message
```
Plugin at '/home/pi/.config/naomi/plugins/stt/Deep_Speech' skipped! (Reason: No module named 'deepspeech')
```
So something must have failed. I'll look into that more later.

**Review by aaronchantrill — APPROVED** [review]
After getting Naomi up and running, finally got to testing the main issue.
1) after deleting the ~/Naomi folder, there is no error when starting new bash sessions.
2) issuing the Naomi command does not generate an error until after the "Would you like to" question:
```
$ Naomi
Notice: Naomi Auto Update Failed!
Notice: Would you like to force update Naomi?
Choice [Y/N]: N - Launching Naomi!
python: can't open file '/home/pi/Naomi/Naomi.py': [Errno 2] No such file or directory
```
3) Git-Cloning Naomi back to the ~/Naomi folder and issuing the Naomi command again works fine!

**Comment by AustinCasteel** [comment]
The issues you last mentioned are in relation to what I said above however, the deepspeech issue is something completely different. Even though it has not been updated for over a year, it's still not deprecated and you can still pip it so it makes no sense why it did not install correctly when you chose to install it.

**Pull request merged**
