### PR TITLE
Fixed Broken Links in Readme

### PR DESCRIPTION
**Pull request by Akhsuna07**
## Description
Fixed the Broken Link in the readme file

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by aaronchantrill — APPROVED** [review]
It appears that the LGTM has been subsumed into Github code scanning, and the LGTM.com website is no longer a thing, so yes, this link and image should be removed from the README.md file. It might be that it could be replaced with something else. I'm not sure. From what I'm reading, it appears that the functionality is now built into Github, but I'm not sure if that is something that has to be enabled for a particular repository.

The next link and image related to requires.io also appear to be defunct.

I'm not sure why there is an empty hyperlink around the blue python badge that precedes these two links, or what the meaning of that badge is.

**Review by aaronchantrill — CHANGES_REQUESTED** [review]
@Akhsuna07 I'm inclined to accept this, but you would have to accept the contributor license agreement first.

**Comment by aaronchantrill** [comment]
I haven't heard back from the requestor and they have not signed the CLA, so closing.

**Comment by niranjan-kurhade** [comment]
> I haven't heard back from the requestor and they have not signed the CLA, so closing.

Hey @aaronchantrill, I would love to work on this issue.
What should the badge be replaced with?
Let me know.

**Comment by aaronchantrill** [comment]
@niranjan-kurhade, thank you for offering to help. I don't think either of them would have to be replaced with anything. Just removing them would be enough.

Thank you,
Aaron

**Pull request closed without merging**
