### PR TITLE
Unit tests for google stt plugin, updated docs and credentials json

### PR DESCRIPTION
**Pull request by olest**
Unit tests for google stt plugin, updated docs and store location of credentials json in user profile.

## Description
The unit test use the template of the pocketsphinx tests. 
What could be added is to set the location of the credentials json in the populate script. Right now the user need to set this manually.

## Related Issue
This is a follow up to issue
https://github.com/NaomiProject/Naomi/issues/166

## Motivation and Context
Documentation was outdated, unit tests missing.

## How Has This Been Tested?
Added unit tests, tested only on Ubuntu laptop but don't see a reason why this shouldn't work on a raspberry pi.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by aaronchantrill** [comment]
Thanks for continuing to work on this. I changed the target from master to naomi-dev. I'm not sure why it is showing the changes to google.py as conflicts rather than just updates. I'm looking through your code now and will have a review soon with a couple of suggestions, but overall this looks good.

**Comment by aaronchantrill** [comment]
One thing I notice is that for the test, you are checking to see if the environment variable is set, and blocking the test if not, which is good, but in the plugin itself you are loading the authorization file based on a value in profile.yml. I think both the plugin and the test probably need to respect both methods, or at least need to agree. I'm not sure which should take precedence if both are used, but I feel like the environment variable probably should trump the profile.yml setting (since it can be set on the command line directly before the executable and thus would be considered more immediate).

**Comment by olest** [comment]
Thanks for the swift response and sorry about the dev/master mess up. I should have known better.

I find having to set environment variables before some plugin works a bit painful, ideally the user would have to set everything only in one place, the profile.yml. But I don't have a strong opinion about this.

So just to clarify, you suggest that both plugin and unit test check for the environment var and in profile.yml but the environment variable takes precedences in both cases?

**Comment by aaronchantrill** [comment]
Yes, my recommendation would be exactly what you said. Storing the location of the authorization file in profile.yml makes sense to me as it is more consistent, but since the google instructions you link to give the environment variable method, it seems wise to also honor that method.

By the way, if you would include the following block of code in the header to the GoogleSTTPlugin class, then the user should be prompted for the location the first time they run Naomi or any time they use the --repopulate flag:

```
    settings = OrderedDict(
        [
            (
                ("google", "authentication_json"), {
                    "type": "file",
                    "title": "Google application credentials (*.json)",
                    "description": "This is a json file that allows your assistant to use the Google Speech API for converting speech to text. You need to generate and download an google cloud API key. Details here: https://cloud.google.com/speech-to-text/docs/quickstart-protocol",
                    "validation": lambda filename: os.path.exists(os.path.expanduser(filename)),
                    "invalidmsg": lambda filename: "File {} does not exist".format(filename),
                    "default": os.getenv('GOOGLE_APPLICATION_CREDENTIALS')
                }
            )
        ]
    )
```

I'm still working on the documentation for that feature.

**Comment by aaronchantrill** [comment]
I have tested this. I have looked into the codacy issue, and it appears to be that instead of writing the "invalid msg" function as `lambda filename :  "File {} does not exist".format(filename)` it wants it as `"File {} does not exist".format` which is my bad. I had no idea that was something codacy would react to.

I did run into a couple of small issues while testing, which are almost too small to even mention, but I wanted to provide the feedback.

First, grpc is a python package that is a requirement of the google-cloud-speech package but does not get pulled in when you install that package, so I had to use `pip3 install grpcio` to install it. I didn't install from scratch this time, so it's possible that it's just a problem on my machine. I'll try to test on a clean Raspbian install on a Raspberry Pi later and verify if this is an issue or not.

Second, if you don't have a valid credentials file defined, the error you get is:
```
Traceback (most recent call last):
  File "~/Naomi_git/plugins/stt/google-stt/google.py", line 61, in __init__
    cred = service_account.Credentials.from_service_account_file(credentials_json)
  File "/usr/local/lib/python3.5/dist-packages/google/oauth2/service_account.py", line 209, in from_service_account_file
    filename, require=['client_email', 'token_uri'])
  File "/usr/local/lib/python3.5/dist-packages/google/auth/_service_account_info.py", line 71, in from_filename
    with io.open(filename, 'r', encoding='utf-8') as json_file:
TypeError: invalid file: None
```
which is a little hard to interpret. Adding something like this might be helpful:
```
credentials_json = profile.get_profile_var(["google", "credentials_json"])
if(credentials_json is None):
    raise FileNotFoundError("Google Speech to Text credentials file is not defined in profile.yml")
elif(not os.path.isfile(credentials_json)):
   raise FileNotFoundError("Google Speech to Text credentials file {} does not exist".format(credentials_json))
cred = service_account.Credentials.from_service_account_file(credentials_json)
```
which generates an error more like:
```
Traceback (most recent call last):
  File "~/Naomi_git/plugins/stt/google-stt/google.py", line 62, in __init__
    raise FileNotFoundError("Google Speech to Text credentials file {} does not exist".format(credentials_json))
FileNotFoundError: Google Speech to Text credentials file  does not exist
```

Other than those three very minor issues, it all works great, so I'm going to go ahead and merge it. Thanks again for helping with this.

**Pull request merged**
