### PR TITLE
First attempt at fixing the profile generator

### PR DESCRIPTION
**Pull request by aaronchantrill**
I re-wrote populate.py and added a hook to application.py to call populate.py if the ~/.jasper/profile.yml (or whatever os.path.join(paths.CONFIG_PATH,"profile.yml") works out to be) file is missing. It's still far from perfect, but I got it to run all the way through and generate a valid "profile.yml" file by mostly accepting the defaults.

There are sure to still be bugs in there, since my testing has not been at all thorough yet, so please let me know if it blows up on you and I'll be happy to fix it. I see this as a place to start collecting the options that people are using, and hope it will be useful as folks work to fix the front end.

For example, I realized that it needs to be integrated into some kind of symmetric encryption scheme so people's email passwords aren't stored in plain text on their computer.

Also, even if you don't enter an email address or phone number, it still demands to know which you prefer for alerts and reminders and won't allow you to proceed without choosing one. If only one option exists, it should use that. If neither option exists, the question makes no sense. I also can't see where this fits into the main application, so I think it's probably there as part of configuring a plugin. This should really be done within the plugin if the necessary configuration issues don't exist, or maybe within a plugin-specific yaml file.

Finally, it frustrates me that it wants me to look up a wikipedia page to locate my time zone. It should be able to figure that out from my zip code, which is the question above. At the least, it should list a few popular options (US, GB, France, Germany, etc).

Things to think about.

Thanks!

### CODE REVIEW

**Comment by AustinCasteel** [comment]
I reviewed the code and everything looked fine to me, so I copied over the changes to my installation. I made a spelling change and then altered the naming of things that go along with my installation and proceeded to run the populate.py.

The run was broken by "Attempted relative import in non-package" from . import i18n on line 9.

**Comment by aaronchantrill** [comment]
Ah, I didn't think to test it running by itself, only pulled in as a function of application.py because I was thinking of it as just as a helper for when the config file needs to be created. Rather than running it directly if I needed to re-create the profile.yml, I would have deleted or renamed the current profile.yml file. Since it doesn't read the current contents of profile.yml at the beginning, there is no real purpose in running it once a profile exists, but I can see that it needs to run both ways.
It did actually pass all the unit tests. I'll fix that and re-submit. Thank you.

**Comment by aaronchantrill** [comment]
Okay, I was able to test on my machine and it all worked regardless of whether I was calling populate.py directly or through the jasper class.

**Comment by aaronchantrill** [comment]
A couple of additional things - I should generate a list of audio input and output devices and allow the user to select the correct one. This is a little more than I have time for right now, but would make the whole thing much more helpful, especially on the Raspberry Pi with its lack of a default microphone. This functionality was not in the original populate.py so nothing lost, and this is at least somewhat better than it was.

Sorry about the flake8 stuff, but unfortunately I chafe at Python's ideas of correct style.

**Comment by aaronchantrill** [comment]
I'm cleaning up the flake8 issues now. I'm really not sure why it's still in a failed state at this point.

**Pull request closed without merging**
