### PR TITLE
Further installer cleanup & features

### PR DESCRIPTION
**Pull request by AustinCasteel**
## Description

- Added an installer dir to hold the platform specific setup scripts
- Allow for an uninterrupted install process with sudo verification
- Script now detects if it is being ran from the source or as the oneliner
- Added jq as a dependency for json parsing
- Implemented auto updates if you select the nightly version of Naomi. Auto updates for the other versions coming soon
- Fixed script permissions
- Auto update also checks for changes & updates for various Naomi dependencies

## Related Issue

There are no currently open related issue

## How Has This Been Tested?

To test the new features you need to run the setup process through the source and select Nightly as your version. Once Naomi is in working order, start Naomi using the script or terminal command and see if it checks for updates.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by aaronchantrill — APPROVED** [review]
Overall, this is a great step forward in getting Naomi configured.

I tested this on a fresh installed copy of Raspbian Buster x86 hosted in a VirtualBox container. After installing, I ran the following commands:
$ git clone --origin=upstream https://github.com/NaomiProject/Naomi.git
$ cd Naomi
$ git fetch upstream pull/275/head:setupscript-cleanup
$ git checkout setupscript-cleanup
$ ./naomi-setup.sh

Here are some small issues I had:
1) The second question is "Would you like the setup to run uninterupted or would you like to look over the setup process?" but if you choose option 1 - Proceeding uninterupted, it still stops after an hour or so and asks whether you want the nightly, monthly, or stable version. This is why I tied my "Don't stop to ask me questions" to the user passing in an argument telling the script how they want to set up Naomi. In this case, if the user passed in --stable or --monthly or --nightly, then the install would also proceed without asking questions (although depending on how sudo is set up, the user might still have to enter their password from time to time).

2) uninterrupted has a double "r"

3) If the user does not select to skip prompts and comes to regret their choice after an hour of pressing the spacebar to keep the process moving, it would be really nice of you to allow them to decide they have seen enough and just skip the rest of the prompts. I would suggest "Press 's' to skip the rest of the prompts". This is similar to how Javascript handles a script that pops up a bunch of alert boxes, where it gives the user the ability to check a box to then skip any future alerts.

Beyond those minor complaints (which certainly don't need to be dealt with right now), everything worked great!

**Comment by AustinCasteel** [comment]
I thought I spell checked things but I must of over looked that, it is now fixed.

There is now a prompt within the sudo command where if you pass a 'S' at any time it askes you can switch to the uninterrtupted process, however this is just a one directing change. Once the process starts running uninterrupted you either have to wait for the process to finish or Control-C out of it.

I have moved some things around where now you are asked if you want sudo or not and then immediately you are asked which version. Then from that point on if you said yes to sudo the the process will be uninterrupted.

**Review by aaronchantrill — CHANGES_REQUESTED** [review]
I just downloaded it again and got this:
```
Welcome to Naomi. This process is designed to make getting started with
Naomi quick and easy. This process can take up to 3 hours to complete.
Would you like to continue with the process now or wait for another time?

  Y)es, I'd like the proceed with the setup.
  N)ope, I will come back at another time.

Choice [Y/N]: y - Yes

/home/pi/Naomi/installers/script.deb.sh: line 50: syntax error near unexpected token `then'
/home/pi/Naomi/installers/script.deb.sh: line 50: `    else [ "$SUDO_APPROVE" != "-y" ]; then'

Notice: Naomi Apt Setup Wizard Failed.
```
Sorry. Looks like the 'else' should be an 'elif'

**Review by aaronchantrill — APPROVED** [review]
Okay, everything looks good and worked for me.

**Pull request merged**
