### PR TITLE
Add gettext support to is_positive and is_negative in naomi/app_utils.py #223

### PR DESCRIPTION
**Pull request by fatkaratekid**
## Description
Added gettext support to is_postitive and is_negative. Also added translation, best to my abilities, for German and French.

## Related Issue
Add gettext support to is_positive and is_negative in naomi/app_utils.py #223
[link](https://github.com/NaomiProject/Naomi/issues/223)

## Motivation and Context
Allows more generic multilingual support.

## How Has This Been Tested?
Not tested.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by aaronchantrill — CHANGES_REQUESTED** [review]
This looks good. I'm not sure why you are including a profile parameter, or where you are including the profile from, since you didn't edit the naomi/commandline.py program which is the only program that currently uses these functions. I have tested and without that parameter, your changes work. With it they don't.

What problems did you have getting it to run exactly? I know Naomi is still pretty difficult to set up and get going, and we are looking for feedback about what the biggest hurdles are currently.

If you can just remove the "profile" parameter from the is_negative and is_positive functions, I'll go ahead and merge this.

Thanks,
Aaron

**Comment by aaronchantrill** [comment]
@fatkaratekid are you still working on this? I'd love to merge this and am just waiting for you to remove the profile parameters.

**Comment by fatkaratekid** [comment]
Ah, yes,sorry, I'll be afk for some 2 weeks. I'll finish it then, if not too late. I know it's a minor thing (all together), so shame on me.

**Comment by aaronchantrill** [comment]
I just discovered that this was pulled from Master and being joined back to Master. Current development is being done on the naomi-dev branch. When I attempted to redirect this to the naomi-dev branch, it pulled in changes that we don't want. The Master branch is also still on Python 2 while naomi-dev is on Python 3. The differences are too great to be reconciled. I have uploaded the changes applied to the app_utils.py file from the current naomi-dev branch, and I encourage you to checkout the naomi-dev branch, apply this file to it, and then try resubmitting this patch.

Thank you,
Aaron

**Pull request closed without merging**
