### PR TITLE
Adjusting setup script & python requirements

### PR DESCRIPTION
**Pull request by AustinCasteel**
| Status  | Type  | Env Vars Change |
| :---: | :---: | :---: |
| Ready | Release & Hotfix | No |

## Description

_Adjusting the setup script to move the framework step into the python_requirements.txt as well as adding pyalsaaudio to help mitigate the audio engine population loop._

## Other changes (e.g. bug fixes, UI tweaks, refactors)

_Tweaked the authors to accommodate the new contributions and fix the Naomi Jasper conversion. In addition to adjusting the readme to direct the users to the proper documentation based on use case._

## Related Tickets

* [naomi-dev crashes with german #119](https://github.com/NaomiProject/Naomi/issues/119)
* [Can't finish creating profile.yml if neither pyaudio nor pyalsaaudio modules are installed #120](https://github.com/NaomiProject/Naomi/issues/120)
* [Fix issue where dictionary is lower case #123](https://github.com/NaomiProject/Naomi/pull/123)

## Todos

- [X] Tests
- [X] Documentation

## Deploy Notes

_Setup script & python requirements adjusted as well as the authors & readme tweak_

**Modified scripts**:

- `naomi-setup.sh` : moving framework into python requirements
- `python_requirements.txt` : adding initial framework & pyalsaaudio
- `AUTHORS.md` : added the naomi contributors and fix the jasper naomi conversion
- `README.md` : adjusted documentation section

### CODE REVIEW

**Review by aaronchantrill — APPROVED** [review]
These appear to me to be helpful changes. I like the change from using apt to install python libraries to using pip. I think this will make it easier for people to adapt the setup script to run on non-debian systems.

**Comment by aaronchantrill** [comment]
I just tried this out while building a new test install environment. I had to change the lines
```python-pip```
```python-pyaudio```
to just
```pip```
```pyaudio```
in python-requirements.txt

The pip packages are only for python, so don't include the "python-" prefix that the apt files do.

I also had to apt install portaudio19-dev and libasound2-dev to get pyaudio to actually install, which does not appear to be included in naomi-setup.sh. I did not actually run naomi-setup.sh this time, but will next time.

**Review by aaronchantrill — DISMISSED** [review]
Please see previous comment.

**Comment by AustinCasteel** [comment]
The setup script has been adjusted as well as cleaned up along with the python requirements. In additions to resolving the readme conflict.

**Comment by aaronchantrill** [comment]
I'm testing now with a fresh copy of Raspbian Stretch 2018-11-13

**Comment by AustinCasteel** [comment]
New issue & pr templates, readme adjustment for removing Travis badge.

**Comment by aaronchantrill** [comment]
I ran into some additional issues with ./naomi-setup.sh. I'm working on them and will send a pull request to your longshotpro2/Naomi master branch.
After that, I think I'm done with 2.2

**Review by aaronchantrill — APPROVED** [review]
Okay, looks good. Thanks for raising requests to v 2.20 to avoid vulnerability. Descriptions in templates look clear. My only question would be related to "related issues" in the pull request template. It makes it look like if I have a new feature I want to share, and am in the middle of a pull request, I just need to stop and create a new issue describing my feature, then put a reference to the issue here. Which is fine with me, but I'm still not completely clear on whether new features have to "blessed" before people can work on them, or what that process would look like.

**Comment by AustinCasteel** [comment]
@aaronchantrill The thought process was so that all info can be fleshed out in an open discussion in an issue to layout the footing for the idea and subsequent PR. So determining whether or not the idea should be implemented, put on hold due to other issues or pr, or abandoned if it does not fit into the scope. Its just a regulatory process to aid in flow & organization.

**Pull request merged**
