### PR TITLE
Add Detailed README for Padatious TTI Plugin

### PR DESCRIPTION
**Pull request by aryan0931**
This PR adds a detailed `README.md` for the Padatious TTI Plugin, including an overview, installation steps, and usage instructions. It also provides contribution guidelines and example usage, improving the documentation for better user and developer understanding.

### CODE REVIEW

**Review by aaronchantrill — CHANGES_REQUESTED** [review]
This readme looks good, but there are a couple of technical problems.

First, this is going into the Naomi repository, where you have just removed the padatious_tti plugin. It should be going into the naomi_plugin_padatious_tti repository instead.

Second, in order for the plugin to show up correctly in the NPE plugins page (https://projectnaomi.com/plugins/), the readme.md has to have a bunch of extra tags that are best generated using the NPEEditor here: https://npeeditor.projectnaomi.com/

One of the requirements is that the name of the file be all lowercase (I keep trying to make mine all uppercase also since that's more traditional but the software really insists on all lowercase).

Go to the NPEEditor page (https://npeeditor.projectnaomi.com/) and fill in the information using values from the plugin.info file. Then, when you have the generated file you can plug this information back into it, and make the pull request against the new repository.

I know this is a pain, and the process of submitting plugins to Naomi is one of the things I'd really like to see simplified and improved, so I'd love to hear any thoughts on how we could improve the process.

Thank you.

**Comment by aaronchantrill** [comment]
I wanted to mention one more thing. The installation instructions are good for a manual install, but we have a tool built into Naomi that allows plugins to be installed from the command line. This is how we encourage users to install plugins, to make sure that the pip requirements get installed to the correct environment and everything gets set up correctly.

To install a plugin, what you would do is use a command like:
```
$ Naomi --list-available-plugins
```
to get a list of plugins like this:
```
Available Plugins:
Announcements (notificationclient [1.0.0 installed]) - Naomi makes announcements at scheduled times.
Archive Audiolog (stt_trainer [1.0.0]) - Allows the user to export their audiolog database and audio files into an archive file that can be merged into a different Naomi using the Import Audiolog plugin.
Chuck Norris Jokes (speechhandler [1.0.0]) - Have Naomi tell random Chuck Norris Jokes
Control LED (speechhandler [1.0.2 installed: 1.0.1]) - A simple module that combines Naomi and the Arduino platform to show possibilities in IOT and new interactions.
Dad Jokes (speechhandler [1.0.0 installed: 1.0]) - Have Naomi tell Dad Jokes
Deep Speech (stt [1.0.0]) - Speech-To-Text implementation which relies on the DeepSpeech api
Facebook Birthdays (speechhandler [1.0.0]) - Keep track of Facebook friends' birthdays
Facebook Notifications (speechhandler [1.0.0]) - Get notifications for Facebook events
frotz (speechhandler [0.1.1 installed]) - Would you like to play a game?
Google AIY Voice V1 Visualizations (visualizations [1.0.0]) - Visualizations of Naomi's internal state for the Google AIY Voice V1 kit
googlecalendar (speechhandler [1.1.0]) - Set and retrieve events from your Google calendar
Greetings (speechhandler [0.0.1 installed]) - Light banter
Import Audiolog (stt_trainer [1.0.0]) - Allows the user to import and merge an audiolog archive created by the Archive Audiolog plugin.
NetworkCheck (speechhandler [1.0.1 installed]) - Simple speechhandler plugin, tells if it is connected to a network and what its IP Address is.
NWS Weather (speechhandler [1.0.0 installed]) - Get weather forecasts for US locations from the US National Weather Service.
Piper-TTS (tts [1.0.0 installed]) - Piper speech synthesizer
Pocketsphinx_KWS (stt [0.0.1 installed]) - Keyword recognizer that uses threshold confidence values to match a few words. When combined with a personalized acoustic model, this works reasonably well.
Respeaker 4Mic Volume (visualizations [1.0.0]) - LED Display for SeeedStudio Respeaker
VOSK STT (stt [1.0.0 installed]) - VOSK STT engine
You're Welcome (speechhandler [0.0.1 installed]) - Answers "Thank you" with "You're welcome"
```
Then use a command like:
```
$ Naomi --install "Padatious TTI"
```
to actually install the plugin.

If you can include these directions along with the manual install instructions, that would be really appreciated.

Thank you!

**Comment by aryan0931** [comment]
Go to the NPEEditor page (https://npeeditor.projectnaomi.com/) and fill in the information using values from the plugin.info file.  I am facing some problems in generating this file can you suggest something.

**Comment by aaronchantrill** [comment]
Hey, I'm glad to hear from you! I'd really appreciate any suggestions on how to make this work better. Here are the answers I would put in for the questions:

Brief, speakable plugin name, capitalizing most words. NOTE: Avoid the word "Plugin" in the name.
Padatious TTI

Please provide a version number for your plugin.
1.0.0

License your plugin is under.
MIT

URL to the repository where your plugin is located
https://github.com/NaomiProject/naomi-plugin-padatious-tti.git

Short Description
Allows the Padatious Text to Intent module to be used with Naomi

First and last name
Naomi Project

URL to reach you
https://projectnaomi.com

File name for your plugin image.
<blank>

Select your plugin type:
Text to Intent

Long Description
This is where my long description goes.

Then hit the generate button. This should prompt you to download a file called "padatious-tti.zip". Download that file and unzip it. Inside, you should find "readme.md". Do not rename this file to "README.md" or "Readme.md" - it has to be "readme.md" - all lower case.

Plug the text from your readme, replacing the text "This is where my long description goes."

Please let me know if this is still not working for you for some reason.

Thank you so much!

-Aaron

**Comment by aryan0931** [comment]
i have created a new pull request in naomi_plugin_padatious_tti repository please check.

**Comment by aaronchantrill** [comment]
I merged your pull request. Please let me know if you got credit for it. I edited the "usage" section right afterward. Intents are created in the Naomi speechhandler plugins, and the different TTI (Text to Intent) API's are interchangeable. This is an optional TTI engine that can be used instead of the default "Naomi TTI" engine.

**Comment by aaronchantrill** [comment]
There is one additional pull request I would like you to make, to the plugins.csv file in the naomi-plugins repository:
https://github.com/NaomiProject/naomi-plugins.git
Thank you,
Aaron

**Comment by aryan0931** [comment]
I have created the fourth pull request.

**Pull request closed without merging**
