### PR TITLE
naomi-setup.sh

### PR DESCRIPTION
**Pull request by aaronchantrill**
## Description

I'm working on getting the naomi-setup.sh script working in a basic way.

## Related Issue

[Issue #67 Friendlier initial configuration](https://github.com/NaomiProject/Naomi/issues/67)

## Motivation and Context

We want to make it easy for a new user to get Naomi up and running in a basic way using a default configuration. For right now, that is pyaudio, pulseaudio, pocketsphinx and flite. The goal is to direct the user to this one file, have them run it, and have it come up with a usable system. After that, they can decide if they are interested in working on configuring and training it.

The script describes what it is doing and asks permission every time it needs to use the sudo command, which can be annoying since building Phonetisaurus takes so long. Just run `./naomi-setup.sh --help for a list of command line options. If you pass in an option instead of selecting it from the menu, you won't have to keep pressing keys to keep the installer going.

## How Has This Been Tested?

I have tested this on a Raspberry Pi 4B running Raspbian Buster.
So far I have only tested the VirtualEnvWrapper option. I need to re-flash my pi and try both the custom Python and direct install options and have all of them 

Discovered that the modules installed for the main python instance
do not automatically become available for the virtual python
environment of the same type, so using apt to install
python3-pocketsphinx did not work, since the pocketsphinx module
would not be available to the virtual environment.

I could have just installed the Pypi version through pip, which
should be fine, but it could lead to a situation where the
python module is a different version from the main pocketsphinx.

It's not that big a deal to build pocketsphinx, so I'm opting to
just do that and install the python version from that same build
process.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by aaronchantrill** [comment]
I have tested all three options (Python Virtual Environment, custom compiled Python, Python libraries installed directly into user account) on a Raspberry Pi 4B running Raspbian Buster and an Ubuntu 18.04 virtual machine running under VirtualBox. I have a terrible internet connection here, so spent a lot of time figuring out why the install failed and discovering that some library failed to download but the script continued anyway, and added error handling to stop the install process after such a failure.

**Review by AustinCasteel — CHANGES_REQUESTED** [review]
During the setup process I encountered an error where pulsemixer can not be found thus breaking the following pulse audio commands but does not cause the script to error out and it continues setting up Naomi.

<details><summary>Pulse Shell Code</summary>

```Shell
Notice: this program is about to use sudo to run the following command:
[/home/pi/Naomi]$ sudo ./naomi_apt_requirements.sh
Press 'q' to quit, any other key to continue:

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pulsemixer
./naomi-setup.sh: line 181: pulseaudio: command not found
./naomi-setup.sh: line 183: pulseaudio: command not found
```
</details>

But shortly after the issue I mentioned last week about mock needing Python >=3.6 actually causes the setup to error out...

<details><summary>Mock Shell Code</summary>

```Shell
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting APScheduler
  Downloading APScheduler-3.6.3-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 807 kB/s
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting mock
  Downloading https://www.piwheels.org/simple/mock/mock-4.0.2-py3-none-any.whl (28 kB)
ERROR: Package 'mock' requires a different Python: 3.5.3 not in '>=3.6'
Error installing python requirements:
```
</details>

**Comment by aaronchantrill** [comment]
Hey @AustinCasteel thanks for testing. Can you tell me what your environment is? Are you installing on Raspbian and if so, then what version?

These look like unrelated issues. I can probably remove the pulsemixer requirement if that doesn't work for your OS, although I think it's a pretty standard package. I added some error handling to stop the installer if something goes wrong in the apt_requirements.txt install.

I don't understand why there would be an issue with mock, though. From my computer:
```
$ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mock
>>> mock.version_info
(4, 0, 2)
>>>
```
so it seems like mock 4.0.2 can run on python 3.7+. What version of python are you running?

**Comment by aaronchantrill** [comment]
I assume that you are using python 3.5.x, which is not compatible with mock 4.0.2. I have set mock to version 3.0.5 which is the last version compatible with python 3.5 and below. I also removed pulsemixer since it does not appear to be available on your system, and it is easy enough to set the volume using alsamixer. Finally, I added a check to stop the script if installing the apt packages fails.

**Comment by aaronchantrill** [comment]
There appears to be a problem with the sound subsystem in VirtualBox which causes the server to process audio faster than it can be passed in when using pyAudio or Pulseaudio through Alsa.

If you select Alsa and then select a device, then talking and listening work, but if you are also playing audio through the same physical device that Naomi speaks on, things lock up. You will especially notice this if you attempt to play music with the mpdcontrol plugin. This is the reason I added the "mpdclient: reticent" ("Should I try to be quiet while music is playing?") setting which tries to limit naomi's speaking while music is playing. I also pause the audio from mpd before Naomi speaks, if Naomi has to speak while in music mode.

So it seems we really need to have different defaults depending on whether Naomi is running on virtualbox or not. However, this is only with regards to the defaults in the populate software, which is now controlled by data structures in naomi/application.py

The naomi-setup.sh program appears to work fine regardless of which setup type you choose.

**Review by AustinCasteel — APPROVED** [review]

**Pull request merged**
