### PR TITLE
New Naomi Setup Scripting & Some Cleanup

### PR DESCRIPTION
**Pull request by AustinCasteel**
## Description

Finally after two years, the new setup script is done.
- The new script now detects what OS & Version of the device it is ran on to manage as well as lay the ground work for various linux distros (deb or rpm), macos, windows, etc. for when we are ready to support further platforms down the road.
- Added the Naomi icon to the root directory because the script now creates a desktop shortcut to start Naomi.
- Naomi can now be started just by opening a terminal and typing `Naomi`.
- Within the setup script you can select which version of Naomi you would like to use (stable, milestone, or nightly).
- Implemented the ground work for auto updating for if a user selects the Nightly version or if they manually enable it.
- Adding in localization options to help prevent none UTF-8 crashes.
- Updated `colorformatting.py` to include the new default color scheme.

## Related Issue

[Non-UTF-8 locale's crash Naomi #190](https://github.com/NaomiProject/Naomi/issues/190)
[Friendlier initial configuration #67](https://github.com/NaomiProject/Naomi/issues/67)

## Motivation and Context

To allow for a smoother user experience when setting up Naomi on any platform or system. The new script will walk you through the process and install the basics to get Naomi running out of the box.

## How Has This Been Tested?

These changes have been test on a Raspbian based VM as well as an Ubuntu machine, both returning satisfactory results.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by aaronchantrill — CHANGES_REQUESTED** [review]
I'm testing on a fresh 2020-02-13-raspbian-buster-lite.img system. I am using the one-liner `. <( wget -O - https://installers.projectnaomi.com/naomi-setup.sh )`.

Before I started, I used raspi-config to set up my locale (en-US.UTF-8), wifi country, and wifi SSID and password. Then I used apt to upgrade my system. This is generally how I always set up new Raspbian machines before I start doing anything to them.

The only showstopping error I ran into was when creating the ~/.config/naomi file structure. It seems that the home directory skeleton for Raspbian lite does not include a .config directory, so when I got to that part I got the following error messages:

```
Creating File Structure...
mkdir: cannot create directory ‘/home/pi/.config/naomi/’: No such file or directory
mkdir: cannot create directory ‘/home/pi/.config/naomi/configs/’: No such file or directory
mkdir: cannot create directory ‘/home/pi/.config/naomi/scripts/’: No such file or directory
mkdir: cannot create directory ‘/home/pi/.config/naomi/sources/’: No such file or directory
```
I would suggest replacing the code used to create these directories with `mkdir -p ~/.config/naomi/{configs,scripts,sources}`.

I still don't understand the first question, which allows you to escape the setup before doing anything. It feels as if something was supposed to have occurred before. As it is, I just went to the trouble of running the program, so why would I want it to exit without doing anything?

I also don't understand why we are forcing the user to select one of four locales. The locale does not have to match Naomi's locale. We just need the user to use the UTF-8 character set, not some ISO-8859 character set. I would just check to see if the currently selected locale is UTF-8 and if not, then find a locale with the same descriptor that is UTF-8. For instance, if someone has selected "en-AU.ISO-8859-1" you should inform them that they need to use a UTF-8 character set and offer to switch them to "en-AU.UTF-8" instead. If you force them to switch to either "en-US.UTF-8" or "en-GB.UTF-8" , they may get annoyed by date, currency or number formatting and switch it back. Since they don't know that the UTF-8 part is important, they are as likely to choose the ISO-8859 version which will then cause Naomi to mysteriously start failing the next time they start it.

If you can fix the first issue, then I'll approve it since the second and third issues are merely annoying and probably fine for most people.

Other than those issues, everything else seemed to work fine.

I like the ability to just run Naomi without having to go to the Naomi directory and running ./Naomi. I also think it will be very helpful to people that you end up in the Naomi virtual environment after Naomi shuts down. I think this will make debugging much easier, especially for those familiar with python who may try to fix an error message about a missing module by installing the module with pip3, then be confused as to why Naomi can't see it when python3 can. Finally, I really like the OS detection with the ability to download different, custom scripts for different operating systems.

**Comment by AustinCasteel** [comment]
Currently if you run the script on a rpm based distros, windows, etc. it returns a message about it not being supported and it allows for when we do end up supporting them only a simple addition is needed.

As far as the localization, you aren't forced to only pick those languages there is a skip option. But I also asked if I should included it or not during development but never got a response so I added in the skip option for the time being. I have taken the localization part out and later down the road I will work on a way to detect the locale and if it isn't UTF-8 then spit out a message.

The environment setup with the directories was a good catch and something I should have planned for just in case but over looked.

As far as the first prompt, I am assuming you are referring to the introduction and prompt if someone wants to continue or not. You wanted a message telling people that the process can take up to 3 hours to complete so if they do not have the time at the moment or do not want to run it that was an easy way to stop the process before it even started. I will reword the introduction and prompt to hopefully clear up any confusion.

The changes are live as of this message being posted.

**Comment by aaronchantrill** [comment]
Thanks Austin. I went back and reviewed the log of when I ran the program, and I guess I didn't notice an option to skip the locale step. Here's what it looked like:

```
The list below is based on the supported languages for Naomi.
If there is a language you would like supported please email
contact@projectnaomi.com and let us know.

-bash: \033[1;95mS\033[1;97m: command not found
If you would like to skip this step you can by inputing  as the option.

Select your locale from the list below:


  1) en_GB
  2) en_US
  3) fr_FR
  4) de_DE

Choice [1-4]: 2 - Enabling en_US UTF-8
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
```
So it looks like something happened and the 'S' to skip option just didn't show up in the output. I also probably just missed the output message because it wasn't clearly tied to the question, and the question prompt only suggest 1-4 as possible options, not 1-4 or 's' to skip.

The other option does appear just after you put a message about the process taking 3 hours, so that makes more sense to me now, but I didn't even notice that message when running it yesterday. I would change the options to "Y)es, give me the guided setup (may take about 3 hours)" and "N)o, quit to the command line" or something like that. As it was, I didn't even notice the message about 3 hours.

Is there a way to tell the setup script not to ask for confirmation? I like the confirmations every time it runs a program, but it does get annoying after a while. It would probably be good to add an option to "s)kip future prompts" so after three or four prompts the user can switch to not having to type a key every time Naomi performs another action.

I'm testing again.

**Comment by AustinCasteel** [comment]
From what you pasted it looks like there was an error with the printf which messed up that line. But nevertheless that section is now on a 3 second pause and then continues for the time being.

**Comment by aaronchantrill** [comment]
I tried pulling your pull request into my test machine using the new github-cli client with 
```
$ gh pr checkout 274
Notice: authentication required
Press Enter to open github.com in your browser... 
From https://github.com/NaomiProject/Naomi
 * [new ref]         refs/pull/274/head -> setupscript-cleanup
Switched to branch 'setupscript-cleanup'
```
Then I ran ./naomi-setup.sh and got this response:
```
      ___           ___           ___           ___                  
     /\__\         /\  \         /\  \         /\__\          ___    
    /::|  |       /::\  \       /::\  \       /::|  |        /\  \   
   /:|:|  |      /:/\:\  \     /:/\:\  \     /:|:|  |        \:\  \  
  /:/|:|  |__   /::\~\:\  \   /:/  \:\  \   /:/|:|__|__      /::\__\ 
 /:/ |:| /\__\ /:/\:\ \:\__\ /:/__/ \:\__\ /:/ |::::\__\  __/:/\/__/ 
 \/__|:|/:/  / \/__\:\/:/  / \:\  \ /:/  / \/__/~~/:/  / /\/:/  /    
     |:/:/  /       \::/  /   \:\  /:/  /        /:/  /  \::/__/     
     |::/  /        /:/  /     \:\/:/  /        /:/  /    \:\__\     
     /:/  /        /:/  /       \::/  /        /:/  /      \/__/     
     \/__/         \/__/         \/__/         \/__/                 

Detected operating system as raspbian/buster.
Checking for curl...
Detected curl...
(Naomi) pi@naomiaustinsetup:~/Naomi $ 
```
I assume this means that the script recognized that Naomi had already been set up, but it would be nice to get some kind of message like "Naomi has been setup. To start Naomi just type 'Naomi' at the prompt". Meanwhile, I'm not sure how to get it to set-up again.

I tried removing the whole ~/.config directory and that allowed the program to run again.

**Comment by AustinCasteel** [comment]
So the script looks for the profile.yml. If there is one the setup does not run. I can add in a check for if there is a profile then say something like:
```
It looks like you already have Naomi installed.
To start name just type `Naomi` in any terminal.

Note: if you are getting this message but have not ran the
setup before or if you have installed Naomi in the past, please
remove the profile.yml from the .config/naomi/configs/ directory.
```

**Review by aaronchantrill — APPROVED** [review]

**Pull request merged**
