### PR TITLE
introduced text-to-intent (tti) handling

### PR DESCRIPTION
**Pull request by andweber**
I've tried to start this discussion already for the "old" jasper project. I'm still convinced that this is something jasper or j2f should explore and go forword - maybe not in this kind of implementation but in some other means.

**Rationale**

Currently jasper is working like this:
1. converting speech to text 
2. passing text to plugins one by one, letting plugins decide who feels responsible for text
3. converting text back to speech

Jasper leaves it to the speechhandling plugins how they are extracting the intent from the phrase or keywords. Most plugins just use simple keyword searching. To improve Jasper this should be more sophisticated or at least be able to improve later one. Currently this is blocked because each plugins implements its own way and thus it can only be improved by improving the plugins.

I created a new plugin class named TTI (text-to-intent)-Mapping. The idea is to return from a given text what the user wanted to do. Thus making the "speechhandling plugins" to "action_plugins" implementing various actions linked to an intent definition. And the TTI as a translator between the transcribed text and the action.

This decouples the recognition of what the user wanted from the plugins, making this more generic and giving the possibility to improve this later on.

**Changes**

So far, basically I integrated the Phrasematcher from jasper-client#134 into a plugin and made it available for the speechhandler plugins.

I created a new plugin class with intent that there might be other kinds of matching implementations later on and (with a config system for plugins) that plugin may choose which TTI they use.

I needed to divide the initialization of STT-Plugins into two steps to be able to pass mic and TTI to the speechhandling plugins during instance creation.

**Example**

Its the sample from jasper-client#134: Have a look at test_phrasematcher.py.

I'm open for ideas, suggestions and discussion.

### CODE REVIEW

**Comment by TuxSeb** [comment]
sorry but i don't understand what do you want to do ..

**Comment by G10DRAS** [comment]
adapt is one such Intent parser used by MycroftAI.
https://github.com/MycroftAI/adapt

Easy to integrate with Jasper.

**Comment by andweber** [comment]
There should be some abstracted way of finding what the user wants and which plugin should serve this:
If you say: "What time is it?" Or "What time do I meet Bob"

There are two points:
1. Jasper brain must be able to put this request to the right plugins (time and calendar in the example). A time plugin simply crapping for the keyword "time" would handle both - giving calendar no chance. You need to look for patterns instead of single keywords.
1. Plugins might want to extract more information than just: I'm now responsible for handling. In the example the calendar plugins needs to understand that the time is wished and it needs the name or subject of the calendar entry. Once again you need to look for patterns.

Currently that's not solved in jasper. The first point is not yet addressed. It's assumed that there are no conflicts in keywords and first plugin in the list feeling responsible is always the right one. The second point is left to the plugins, handled there more or less sophisticated.

My point is - there should be a layer in jasper handling this. I proposed an generic approach putting this to a plugin - which might get too complex that some point - I don't know. 
The other way would be to implement some logic, which might be too limited for some use cases. Plugins are more flexible and I it can be more easily improved later on. That was the reason starting with simple regex matching and later on this can be improved.

This "adapt" looks interesting at a first glance, I will have look at it - or are you already firm with it @G10DRAS? 
With the plugin approach it could be an alternative to the phrasematching approach.

**Comment by G10DRAS** [comment]
I tried adapt in the past but not tested with Jasper.
Take a look at this thread
https://github.com/MycroftAI/adapt/issues/7

**Comment by G10DRAS** [comment]
I tried adapt in the past but not tested with Jasper.
Take a look at this thread
https://github.com/MycroftAI/adapt/issues/7

**Comment by chrobione** [comment]
I agree that there needs to be a de-coupling of the intent part from the plugins and that the brain should be putting the data to the right plugin.   I like the adapt approach, but with the numbers being ambiguous unless they are numeric concerns me.  I am not sure on the correct path as of yet.

More testing required.

**Comment by AustinCasteel** [comment]
Abandoning pull request due to being out of date. Make a new issue & pull request referencing this one if this needs to be reopened.

**Pull request closed without merging**
