### PR TITLE
Updating Deb Install to Reflect New Nightly Builds

### PR DESCRIPTION
**Pull request by AustinCasteel**
## Description

We finally ran into our first problem with Bintray being our choice of universal distribution platform to handle how we publish, store, promote, and distribute software. Last week our nightly builds of Naomi stopped getting published but went unnoticed until last night when the GitHub action that handles the processing faulted when trying to publish the nightly build to Bintray.

Apparently Bintray has a limit for how long a version can be used, in our case we have had the nightly version deleted and republished with any new code on a nightly bases for 365 days. Since we hit 365 days Bintray wants a new version made, but since we do not archive nightlys and just replace them they do not have any semantic naming. They have always been called "Naomi-Nightly.zip".

To fix this issue, I now "build" the source and then push it to the same file server as the installer files. The nightly build has also been changed to not run on a nightly bases but rather whenever anything is pushed/merged into naomi-dev. So in essence it is the same however it wont be hitting the file server every single night but rather whenever there is an update to any code just the installer files are done.

This PR is to provide all the relevant information for the last couple changes I have made to get this working as well as merge in the update to the deb installer file to reflect the new url the nightly zip file is located.

## Related Issue

[PR#298](https://github.com/NaomiProject/Naomi/pull/298)
[PR#301](https://github.com/NaomiProject/Naomi/pull/301)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by aaronchantrill** [comment]
@AustinCasteel I will test this by downloading the installer onto a fresh raspbian and choosing nightly. Do I need to test anything else?

**Comment by AustinCasteel** [comment]
@aaronchantrill Nope, as long as the installer can pull the nightly version then all things should be good.

**Comment by aaronchantrill** [comment]
I will test this tomorrow.

**Review by aaronchantrill — COMMENTED** [review]
I ran it and selected "Nightly" and it was able to download from https://installers.projectnaomi.com. However, when I did a `git pull origin` I got quite a few updates:
```
$ git pull origin
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 41 (delta 25), reused 34 (delta 20), pack-reused 0
Unpacking objects: 100% (41/41), done.
From https://github.com/NaomiProject/Naomi
   1e5ef7b..059acf0  naomi-dev  -> origin/naomi-dev
Updating 1e5ef7b..059acf0
Fast-forward
 .github/workflows/nightly-publish.yml | 17 ++++++++++-------
 .gitignore                            |  1 +
 plugins/speechhandler/joke/joke.py    |  6 +++---
 plugins/tti/naomi_tti/naomi_tti.py    | 37 ++++++++++++++++++++++++++-----------
 4 files changed, 40 insertions(+), 21 deletions(-)
```
so it pulled in changes from early in October. Not exactly the latest code. I'm not sure if you are counting on Naomi checking for and downloading updates when you first start it up.

I'm not sure what exactly you are expecting.

**Comment by AustinCasteel** [comment]
Regardless how Naomi checks for updates and actually does it, the downloaded nightly should have been the latest therfore including those changes back in early October.

I will look through the complete workflow and try to find what the issue is.

**Comment by aaronchantrill** [comment]
I'll try again and look for those changes specifically.

**Comment by aaronchantrill** [comment]
I manually downloaded the repository and it appears to have the changes:
```
pi@naomitestpi:~/Temp/Naomi-Nightly $ git log
commit 059acf056b3f69e463439ab6ed360ad1e1b5bf92 (HEAD -> naomi-dev, origin/naomi-dev, origin/HEAD)
Merge: b3fae37 5889025
Author: Austin Casteel <austin.casteel@gmail.com>
Date:   Sun Nov 1 00:33:57 2020 -0500

    Merge pull request #301 from AustinCasteel/fixing-nightly-builds
    
    push vs hitting server every night with no change
```
I'm trying the full install again.

**Comment by AustinCasteel** [comment]
After looking over all the code that could possibly effect it, I see nothing. Everything should be sound and I have no idea why it didn't work for you the first time.

**Comment by aaronchantrill** [comment]
Me either. Sorry, I never got the time to do a full reinstall this afternoon. I'll get it done tomorrow.

**Comment by aaronchantrill** [comment]
Okay, I think I understand what happened now. I downloaded your copy of installers/naomi-setup.sh which downloads and runs the script.deb.sh script from github.com/ProjectNaomi/Naomi, so I just ended up running the old code. I just tried downloading just the script.deb.sh script, but it errored out with the message "./naomi_apt_requirements.sh command not found". It appears that if you run naomi-setup.sh it will always download the latest version of script.deb.sh, so downloading your whole repository wouldn't help.

I ended up downloading installers/script.deb.sh, naomi_apt_requirements.sh, and apt_requirements.txt into the same folder, then just ran script.deb.sh directly. I'm still in the process of installing, I'll update when installation completes

**Comment by aaronchantrill** [comment]
This time it worked as expected:
```
pi@naomitestpi:~ $ ./script.deb.sh
pi@naomitestpi:~ $ cd Naomi
pi@naomitestpi:~/Naomi $ git branch
* naomi-dev
pi@naomitestpi:~/Naomi $ git remote -v
origin	https://github.com/NaomiProject/Naomi.git (fetch)
origin	https://github.com/NaomiProject/Naomi.git (push)
pi@naomitestpi:~/Naomi $ git pull origin
Already up to date.
```

**Pull request merged**
