### PR TITLE
Allow to enable only certain speechhandlers by configuration

### PR DESCRIPTION
**Pull request by sbernhard**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by aaronchantrill** [comment]
I'm changing this to point to naomi-dev branch, where the magic is happening, unless you have some reason you want this pushed to the current stable branch.

**Comment by sbernhard** [comment]
sure, from other projects I'm used to it, that master is the development branch.

**Comment by aaronchantrill** [comment]
Okay, thanks. And thanks for contributing!

Here is how I read this plugin. If you create a "speechhandlers" block in your profile.yml file, then only those speechhandlers listed will be used. Can you clarify the structure of that block?

Also, I think it might be helpful to make this more of a block feature than an include feature, because as written, the user would have to go through and figure out the names of all their current plugins and add them to a list just to block the one plugin they don't want to use.

I can imagine an implementation where Naomi automatically adds any speechhandler plugins it finds to the list with a "Yes" value, and the user can disable particular plugins by changing that value to "No". Something like:

load_speechhandlers:
  weather: No
  joke: Yes

That sort of thing.

Also, I don't think the changes to readme really work. In both cases, we are trying to allow the user to visit the main project website (http://projectnaomi.com) by clicking links in the readme page.

I have to run out for a minute, when I get back, I will look at the other pull requests.

Thanks, Aaron

**Comment by sbernhard** [comment]
The block looks like this:
speechhandlers:
  - clock
  - mpdcontrol


This is pretty easy. If the block doesn't exist, all plugins are loaded. Otherwise, only the items listed. 

The Readme change is because the change from master to naomi-dev I think.

**Comment by AustinCasteel** [comment]
The readme conflict was because the master readme didn't change back once we got the site back up and running. The readme has now been fixed. Sorry about the confusion.

**Comment by sbernhard** [comment]
Looks like #32

**Pull request merged**
